#!/usr/bin/env node
/**
 * build-display.js — Bundle ES modules into display.js UMD for Node and browser
 *
 * Reads from: src/lib/display/ (ES modules)
 * Outputs to: display.js (UMD bundle)
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '../src/lib/display');
const outFile = path.join(__dirname, '../display.js');

// Read CSS and escape for JS string
const cssPath = path.join(srcDir, 'tokens.css');
const cssContent = fs.readFileSync(cssPath, 'utf8');
const cssEscaped = JSON.stringify(cssContent);

// Plugin to handle ?raw imports by inlining the CSS
const rawCssPlugin = {
  name: 'raw-css',
  setup(build) {
    build.onResolve({ filter: /\.css\?raw$/ }, args => ({
      path: args.path,
      namespace: 'raw-css'
    }));
    build.onLoad({ filter: /.*/, namespace: 'raw-css' }, () => ({
      contents: `export default ${cssEscaped};`,
      loader: 'js'
    }));
  }
};

async function build() {
  try {
    await esbuild.build({
      entryPoints: [path.join(srcDir, 'index.js')],
      bundle: true,
      format: 'iife',
      globalName: 'display',
      outfile: outFile,
      plugins: [rawCssPlugin],
      // Add UMD compatibility footer
      footer: {
        js: `
// UMD compatibility: export to CommonJS if available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = display;
}`
      },
      banner: {
        js: `/**
 * display.js — Universal Renderer for AIde (auto-generated UMD bundle)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source: frontend/src/lib/display/
 * Build: npm run build:display
 */
`
      }
    });

    console.log('Built display.js successfully');
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

build();
