#!/usr/bin/env python3
"""
Build engine.py - single-file Python kernel build.

Concatenates all kernel modules into a single standalone file with no external dependencies.
The output can be distributed as a single Python file that contains the full AIde kernel.
"""

import re
from pathlib import Path


def remove_imports(content: str) -> str:
    """Remove internal imports and __future__ imports from engine.kernel modules."""
    lines = []
    in_import_block = False
    import_indent = 0

    for line in content.split("\n"):
        stripped = line.strip()

        # Skip __future__ imports (we add one at the top)
        if stripped.startswith("from __future__"):
            continue

        # Skip imports from engine.kernel
        if stripped.startswith("from engine.kernel"):
            # Check if it's a multi-line import
            if "(" in line and ")" not in line:
                in_import_block = True
                import_indent = len(line) - len(line.lstrip())
            continue

        # If we're in a multi-line import block, skip until we find the closing paren
        if in_import_block:
            if ")" in line:
                in_import_block = False
            continue

        if stripped.startswith("import engine.kernel"):
            continue

        # Keep all other lines
        lines.append(line)

    return "\n".join(lines)


def extract_module_content(file_path: Path) -> str:
    """Extract the content of a module, removing imports and docstrings."""
    content = file_path.read_text()

    # Remove module docstring (first multiline string after imports)
    # Keep it for documentation but mark it clearly
    match = re.match(r'^"""(.*?)"""', content, re.DOTALL)
    docstring = ""
    if match:
        docstring = f'"""\n{match.group(1)}\n"""\n'
        content = content[match.end():].lstrip()

    # Remove internal imports
    content = remove_imports(content)

    return docstring, content


def build_engine():
    """Build the single-file engine.py."""
    root = Path(__file__).parent.parent
    kernel_dir = root / "engine" / "kernel"
    output_file = root / "engine" / "builds" / "engine.py"

    # Ensure builds directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Module order matters for dependencies
    modules = [
        "types.py",       # No dependencies
        "primitives.py",  # Depends on types
        "reducer.py",     # Depends on types, primitives
        "renderer.py",    # Depends on types
        "assembly.py",    # Depends on types, primitives, reducer, renderer
        "events.py",      # Utility, minimal dependencies
    ]

    parts = []

    # Header
    parts.append('"""')
    parts.append("AIde Engine - Single-file Python kernel")
    parts.append("")
    parts.append("Complete event-sourced kernel for AIde living objects.")
    parts.append("Pure functions: events → reducer → snapshot → renderer → HTML")
    parts.append("")
    parts.append("This file is generated by scripts/build_engine_python.py")
    parts.append("DO NOT EDIT MANUALLY - Edit source files in engine/kernel/ instead")
    parts.append("")
    parts.append("Usage:")
    parts.append("  from engine import AideAssembly, Blueprint, Event")
    parts.append("  from engine import reduce, render, empty_state")
    parts.append("")
    parts.append("Reference: docs/eng_design/aide_architecture.md")
    parts.append('"""')
    parts.append("")
    parts.append("from __future__ import annotations")
    parts.append("")
    parts.append("# Standard library imports")
    parts.append("import asyncio")
    parts.append("import copy")
    parts.append("import json")
    parts.append("import re")
    parts.append("import uuid")
    parts.append("from dataclasses import dataclass, field")
    parts.append("from datetime import datetime, timezone")
    parts.append("from html import escape as _html_escape")
    parts.append("from typing import Any")
    parts.append("")
    parts.append("")
    parts.append("# " + "=" * 75)
    parts.append("# KERNEL MODULES")
    parts.append("# " + "=" * 75)
    parts.append("")

    # Add each module
    for module_name in modules:
        module_path = kernel_dir / module_name
        if not module_path.exists():
            print(f"Warning: {module_name} not found, skipping")
            continue

        docstring, content = extract_module_content(module_path)

        parts.append("")
        parts.append("# " + "-" * 75)
        parts.append(f"# {module_name}")
        parts.append("# " + "-" * 75)
        parts.append("")
        if docstring:
            parts.append(docstring)
        parts.append(content)
        parts.append("")

    # Footer
    parts.append("")
    parts.append("# " + "=" * 75)
    parts.append("# PUBLIC API")
    parts.append("# " + "=" * 75)
    parts.append("")
    parts.append("__all__ = [")
    parts.append('    # Core functions')
    parts.append('    "empty_state",')
    parts.append('    "reduce",')
    parts.append('    "replay",')
    parts.append('    "render",')
    parts.append('    "render_block",')
    parts.append('    # Assembly layer')
    parts.append('    "AideAssembly",')
    parts.append('    "AideStorage",')
    parts.append('    "MemoryStorage",')
    parts.append('    "parse_aide_html",')
    parts.append('    # Types')
    parts.append('    "Event",')
    parts.append('    "Blueprint",')
    parts.append('    "RenderOptions",')
    parts.append('    "AideFile",')
    parts.append('    "ApplyResult",')
    parts.append('    "ReduceResult",')
    parts.append('    "Warning",')
    parts.append('    # Primitives')
    parts.append('    "validate_primitive",')
    parts.append('    "PRIMITIVE_TYPES",')
    parts.append("]")
    parts.append("")

    # Write output
    output_content = "\n".join(parts)
    output_file.write_text(output_content)

    print(f"✓ Built engine.py ({len(output_content)} bytes)")
    print(f"  Location: {output_file}")
    print(f"  Modules: {', '.join(modules)}")

    return output_file


if __name__ == "__main__":
    build_engine()
